# archi3d/config/adapters.yaml
adapters:
  trellis_multi_stochastic:
    endpoint: "fal-ai/trellis/multi"
    unit_price_usd: 0.02
    price_source: "fal.ai 2025-08 list"
    defaults:
      multiimage_algo: "stochastic"
      texture_size: 2048
      # seed omitted => provider default
  trellis_multi_multidiffusion:
    endpoint: "fal-ai/trellis/multi"
    unit_price_usd: 0.02
    price_source: "fal.ai 2025-08 list"
    defaults:
      multiimage_algo: "multidiffusion"
      texture_size: 2048
      # seed omitted => provider defaults
  tripo3d_v2p5_multi:
    endpoint: "tripo3d/tripo/v2.5/multiview-to-3d"
    unit_price_usd: 0.40
    price_source: "fal.ai 2025-08 list"
    defaults:
      pbr: true          
      texture: "HD"      
      # all other options left to provider defaults
  rodin_multi:
    endpoint: "fal-ai/hyper3d/rodin"
    unit_price_usd: 0.40
    price_source: "fal.ai 2025-08 list"
    defaults:
      condition_mode: "concat"
      material: "PBR"
      quality: "high"
      use_hyper: true   
  hunyuan3d_v2_multi:
    endpoint: "fal-ai/hunyuan3d/v2/multi-view"
    unit_price_usd: 0.51
    price_source: "fal.ai 2025-08 list"
    defaults:
      textured_mesh: true     
      # seed omitted -> provider default
      # other params left at model defaults
