# archi3d/config/adapters.yaml
adapters:
  trellis_multi_stochastic:
    endpoint: "fal-ai/trellis/multi"
    unit_price_usd: 0.02
    price_source: "fal.ai 2025-08 list"
    defaults:
      multiimage_algo: "stochastic"
      texture_size: 2048
      # seed omitted => provider default
  trellis_multi_multidiffusion:
    endpoint: "fal-ai/trellis/multi"
    unit_price_usd: 0.02
    price_source: "fal.ai 2025-08 list"
    defaults:
      multiimage_algo: "multidiffusion"
      texture_size: 2048
      # seed omitted => provider defaults
  tripo3d_v2p5_multi:
    endpoint: "tripo3d/tripo/v2.5/multiview-to-3d"
    unit_price_usd: 0.40
    price_source: "fal.ai 2025-08 list"
    defaults:
      pbr: true          # as requested
      texture: "HD"      # as requested
      # all other options left to provider defaults
  rodin_multi:
    endpoint: "fal-ai/hyper3d/rodin"
    unit_price_usd: 0.40
    price_source: "fal.ai 2025-08 list"
    defaults:
      condition_mode: "concat"   # approved
      material: "PBR"            # approved
      quality: "high"            # approved
      # geometry_file_format left to default "glb"
      # seed omitted -> provider default